chore: bump deps (#221)
* tweak thresholds

* wip

* groth works

* reset shard size

* bump

* change commit + feature flag native gnark

* no more e2e.rs

* native gnark in ci

* bump ci

* revert fancy ci stuff

---------

Co-authored-by: yuwen <yuwen>

diff --git a/.github/actions/setup/action.yml b/.github/actions/setup/action.yml
--- a/.github/actions/setup/action.yml
+++ b/.github/actions/setup/action.yml
@@ -88,15 +88,15 @@ runs:
         . "$HOME/.cargo/env" 
         echo "$HOME/.cargo/bin" >> $GITHUB_PATH
 
-    - name: Install pkg-config, openssl, cmake, and unzip
+    - name: Install pkg-config and openssl
       shell: bash
       run: |
-        if ! dpkg -s pkg-config libssl-dev cmake unzip &> /dev/null; then
-          echo "pkg-config, libssl-dev, cmake, and unzip not found. Installing..."
+        if ! dpkg -s pkg-config libssl-dev cmake unzip libclang-dev &> /dev/null; then
+          echo "pkg-config, libssl-dev, cmake, unzip, libclang-dev not found. Installing..."
           sudo apt-get update
-          sudo apt-get install -y pkg-config libssl-dev cmake unzip
+          sudo apt-get install -y pkg-config libssl-dev cmake unzip libclang-dev
         else
-          echo "pkg-config, libssl-dev, cmake, and unzip are already installed."
+          echo "pkg-config, libssl-dev, cmake, unzip, libclang-dev are already installed."
         fi
 
     - name: Echo docker buildx version
